// Estado = "oferta" - "limitado" - "nuevo" - "agotado" - "exclusivo" - "rebajado" - "proximamente" - "top"
// Tipo Medida: "talle" - "Cm" - "Litros" - "Marca" 

//Img, Estado, Categoria, Codigo, Producto, Talle, PrecioMayor, PrecioMinorista, Descripcion, Color

//Se muestra en el carrito: Img, Producto, Talle, Precio, Color, Cantidad


const productos = [
    {
        Codigo: "P01",
        Estado: "Top",
        Img: "Plantillas/P01-img1",
        Producto: "Común Blanca",
        PrecioMayor: 900,
        PrecioMinorista: 2000,
        Categoria: "Plantillas",
        TipoMedida: "Talle",
        Talle: [21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45],
        Descripcion: "Toalla y goma eva. precio minorista [2000] precio mayorista apartir de 3docenas(36 unidades) solo con talles variados [900]",
        Color: null,
    },
    {
        Codigo: "P02",
        Estado: "Top",
        Img: "Plantillas/P02-img1",
        Producto: "Común Negra",
        PrecioMayor: 950,
        PrecioMinorista: 2000,
        Categoria: "Plantillas",
        TipoMedida: "Talle",
        Talle: [21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45],
        Descripcion: "Toalla y goma eva. precio minorista [2000] precio mayorista apartir de 3docenas(36 unidades) solo con talles variados [950]",
        Color: null,
    },
    {
        Codigo: "P03",
        Estado: "Top",
        Img: "Plantillas/P03-img1",
        Producto: "Arco Blanca",
        PrecioMayor: 1000,
        PrecioMinorista: 3000,
        Categoria: "Plantillas",
        TipoMedida: "Talle",
        Talle: [21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45],
        Descripcion: "Toalla y goma eva. precio minorista [3000] precio mayorista apartir de 3docenas(36 unidades) solo con talles variados [1000]",
        Color: [],
    },
    {
        Codigo: "P04",
        Estado: "Top",
        Img: "Plantillas/P04-img1",
        Producto: "Arco Negra",
        PrecioMayor: 1050,
        PrecioMinorista: 3000,
        Categoria: "Plantillas",
        TipoMedida: "Talle",
        Talle: [21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45],
        Descripcion: "Toalla y goma eva. precio minorista [3000] precio mayorista apartir de 3docenas(36 unidades) solo con talles variados [1050]",
        Color: null,
    },
    {
        Codigo: "P05",
        Estado: null,
        Img: "Plantillas/P05-img1",
        Producto: "Coderito",
        PrecioMayor: 1500,
        PrecioMinorista: 3500,
        Categoria: "Plantillas",
        TipoMedida: "Talle",
        Talle: [34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45],
        Descripcion: null,
        Color: null,
    },
    {
        Codigo: "P06",
        Estado: null,
        Img: "Plantillas/P06-img1",
        Producto: "plantilla talon leal",
        PrecioMayor: 5700,
        PrecioMinorista: 12000,
        Categoria: "Plantillas",
        TipoMedida: "Talle",
        Talle: [37, 38, 39, 40, 41, 42, 43, 44, 45],
        Descripcion: null,
        Color: null,
    },
    {
        Codigo: "P07",
        Estado: null,
        Img: "Plantillas/P07-img1",
        Producto: "Latex",
        PrecioMayor: 3200,
        PrecioMinorista: null,
        Categoria: "Plantillas",
        TipoMedida: "Talle",
        Talle: [34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45],
        Descripcion: null,
        Color: null,
    },
    {
        Codigo: "P08",
        Estado: null,
        Img: "Plantillas/P08-img1",
        Producto: "3D Chico",
        PrecioMayor: 3900,
        PrecioMinorista: 7500,
        Categoria: "Plantillas",
        TipoMedida: null,
        Talle: null,
        Descripcion: "Plantilla Recortable/adaptable a los talles: 35 al 40",
        Color: null,
    },
    {
        Codigo: "P09",
        Estado: null,
        Img: "Plantillas/P09-img1",
        Producto: "3D Grande",
        PrecioMayor: 3900,
        PrecioMinorista: 7500,
        Categoria: "Plantillas",
        TipoMedida: null,
        Talle: null,
        Descripcion: "Plantilla Recortable/adaptable a los talles: 40 al 45",
        Color: null,
    },
    {
        Codigo: "P10",
        Estado: null,
        Img: "Plantillas/P10-img1",
        Producto: "Cuero",
        PrecioMayor: 3800,
        PrecioMinorista: null,
        Categoria: "Plantillas",
        TipoMedida: "Talle",
        Talle: [34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45],
        Descripcion: null,
        Color: null,
    },
    {
        Codigo: "P11",
        Estado: null,
        Img: "Plantillas/P11-img1",
        Producto: "Deportiva",
        PrecioMayor: 3800,
        PrecioMinorista: null,
        Categoria: "Plantillas",
        TipoMedida: "Talle",
        Talle: [34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45],
        Descripcion: null,
        Color: ["Naranja","Negro","Gris","Surtido",],
    },

    {
        Codigo: "MODELO00",
        Estado: null,
        Img: "Llaveros/Modelo00-img1",
        Producto: "Pasacinto con Broche",
        PrecioMayor: 4000,
        PrecioMinorista: 2500,
        Categoria: "Llaveros",
        TipoMedida: null,
        Talle: [],
        Descripcion: null,
        Color: [],
    },
    {
        Codigo: "MODELO01",
        Estado: null,
        Img: "Llaveros/Modelo01-img1",
        Producto: "pascinto con adorno",
        PrecioMayor: 4000,
        PrecioMinorista: 3000,
        Categoria: "Llaveros",
        TipoMedida: null,
        Talle: [],
        Descripcion: null,
        Color: [],
    },
    {
        Codigo: "MODELO02",
        Estado: null,
        Img: "Llaveros/Modelo02-img1",
        Producto: "Pasacinto con Mosqueton",
        PrecioMayor: 4000,
        PrecioMinorista: 3500,
        Categoria: "Llaveros",
        TipoMedida: null,
        Talle: [],
        Descripcion: null,
        Color: [],
    },
    {
        Codigo: "MODELO03",
        Estado: null,
        Img: "Llaveros/Modelo03-img1",
        Producto: "pasacinto alambre",
        PrecioMayor: 4000,
        PrecioMinorista: 2500,
        Categoria: "Llaveros",
        TipoMedida: null,
        Talle: [],
        Descripcion: null,
        Color: [],
    },
    {
        Codigo: "MODELO04",
        Estado: null,
        Img: "Llaveros/Modelo04-img1",
        Producto: "pasacinto vigilante",
        PrecioMayor: 4000,
        PrecioMinorista: 3000,
        Categoria: "Llaveros",
        TipoMedida: null,
        Talle: [],
        Descripcion: null,
        Color: [],
    },
    {
        Codigo: "MODELO07",
        Estado: null,
        Img: "Llaveros/Modelo07-img1",
        Producto: "Huevo con Adorno",
        PrecioMayor: 4000,
        PrecioMinorista: 2500,
        Categoria: "Llaveros",
        TipoMedida: null,
        Talle: [],
        Descripcion: null,
        Color: [],
    },
    {
        Codigo: "MODELO08",
        Estado: null,
        Img: "Llaveros/Modelo08-img1",
        Producto: "llavero huevo con dije",
        PrecioMayor: 4000,
        PrecioMinorista: 3500,
        Categoria: "Llaveros",
        TipoMedida: null,
        Talle: [],
        Descripcion: null,
        Color: [],
    },
    {
        Codigo: "MODELO09",
        Estado: null,
        Img: "Llaveros/Modelo09-img1",
        Producto: "Llavero con Adorno",
        PrecioMayor: 4000,
        PrecioMinorista: 3000,
        Categoria: "Llaveros",
        TipoMedida: null,
        Talle: [],
        Descripcion: null,
        Color: [],
    },
    {
        Codigo: "MODELO10",
        Estado: null,
        Img: "Llaveros/Modelo10-img1",
        Producto: "Dije Herradura",
        PrecioMayor: 4000,
        PrecioMinorista: 3000,
        Categoria: "Llaveros",
        TipoMedida: null,
        Talle: [],
        Descripcion: null,
        Color: [],
    },
    {
        Codigo: "MODELO11",
        Estado: null,
        Img: "Llaveros/Modelo11-img1",
        Producto: "Llavero Boca",
        PrecioMayor: 4000,
        PrecioMinorista: 3000,
        Categoria: "Llaveros",
        TipoMedida: null,
        Talle: [],
        Descripcion: null,
        Color: [],
    },
    {
        Codigo: "MODELO12",
        Estado: null,
        Img: "Llaveros/Modelo12-img1",
        Producto: "Llavero River",
        PrecioMayor: 4000,
        PrecioMinorista: 3000,
        Categoria: "Llaveros",
        TipoMedida: null,
        Talle: [],
        Descripcion: null,
        Color: [],
    },
    {
        Codigo: "MODELO13",
        Estado: null,
        Img: "Llaveros/Modelo13-img1",
        Producto: "Llavero corto 2 remaches",
        PrecioMayor: 4000,
        PrecioMinorista: 3500,
        Categoria: "Llaveros",
        TipoMedida: null,
        Talle: [],
        Descripcion: null,
        Color: [],
    },
    {
        Codigo: "MODELO14",
        Estado: null,
        Img: "Llaveros/Modelo14-img1",
        Producto: "Llavero corto 1 remache",
        PrecioMayor: 4000,
        PrecioMinorista: 3500,
        Categoria: "Llaveros",
        TipoMedida: null,
        Talle: [],
        Descripcion: null,
        Color: [],
    },

    {
        Codigo: "ArtiPr01",
        Estado: "Limitado",
        Img: "ArticulosDePerro/ArtiPr01-img1",
        Producto: "Collar de Perro",
        PrecioMayor: "Consultar",
        PrecioMinorista: "Consultar",
        Categoria: "Articulos de perro",
        TipoMedida: null,
        Talle: ["Chico", "Mediano", "Grande"],
        Descripcion: "Chico:35cm x 1.5cm   Mediano:45cm x 2.0cm   Grande:55cm x 2.5cm",
        Color: [],
    },
    {
        Codigo: "ArtiPr02",
        Estado: "Limitado",
        Img: "ArticulosDePerro/ArtiPr02-img1",
        Producto: "Correa de Perro",
        PrecioMayor: "Consultar",
        PrecioMinorista: "Consultar",
        Categoria: "Articulos de perro",
        TipoMedida: null,
        Talle: ["Chico", "Mediano", "Grande"],
        Descripcion: "Chico:1.2cm x 1.5cm   Mediano:1.2cm x 2.0cm   Grande:1.2cm x 2.5cm",
        Color: [],
    },
    {
        Codigo: "ArtiPr03",
        Estado: "Limitado",
        Img: "ArticulosDePerro/ArtiPr03-img1",
        Producto: "Pretal de Perro",
        PrecioMayor: "Consultar",
        PrecioMinorista: "Consultar",
        Categoria: "Articulos de perro",
        TipoMedida: null,
        Talle: ["Chico", "Mediano", "Grande"],
        Descripcion: null,
        Color: [],
    },

    {
        Codigo: "M01",
        Estado: null,
        Img: "Medias/M01-img1",
        Producto: "Soquete Termico x12",
        PrecioMayor: 10500,
        PrecioMinorista: null,
        Categoria: "Medias",
        TipoMedida: null,
        Talle: [],
        Descripcion: null,
        Color: [],
    },
    {
        Codigo: "M02",
        Estado: null,
        Img: "Medias/M02-img1",
        Producto: "Soquete x12",
        PrecioMayor: 3500,
        PrecioMinorista: null,
        Categoria: "Medias",
        TipoMedida: null,
        Talle: [],
        Descripcion: null,
        Color: [],
    },
    {
        Codigo: "M03",
        Estado: null,
        Img: "Medias/M03-img1",
        Producto: "AntiDeslizantes 1/4 x12",
        PrecioMayor: 22000,
        PrecioMinorista: null,
        Categoria: "Medias",
        TipoMedida: null,
        Talle: [],
        Descripcion: null,
        Color: [],
    },
    {
        Codigo: "M04",
        Estado: null,
        Img: "Medias/M04-img1",
        Producto: "AntiDeslizantes Largas x12",
        PrecioMayor: 25000,
        PrecioMinorista: null,
        Categoria: "Medias",
        TipoMedida: null,
        Talle: [],
        Descripcion: null,
        Color: [],
    },
    {
        Codigo: "M05",
        Estado: null,
        Img: "Medias/M05-img1",
        Producto: "Tenis x12",
        PrecioMayor: 18000,
        PrecioMinorista: null,
        Categoria: "Medias",
        TipoMedida: null,
        Talle: [],
        Descripcion: null,
        Color: [],
    },
    {
        Codigo: "M06",
        Estado: null,
        Img: "Medias/M06-img1",
        Producto: "Termica Piel x12",
        PrecioMayor: 10000,
        PrecioMinorista: null,
        Categoria: "Medias",
        TipoMedida: null,
        Talle: [],
        Descripcion: null,
        Color: [],
    },
    {
        Codigo: "M07",
        Estado: null,
        Img: "Medias/M07-img1",
        Producto: "Soquete Invisible x12",
        PrecioMayor: 3500,
        PrecioMinorista: null,
        Categoria: "Medias",
        TipoMedida: null,
        Talle: [],
        Descripcion: null,
        Color: [],
    },
    {
        Codigo: "M08",
        Estado: null,
        Img: "Medias/M08-img1",
        Producto: "Medias Aitana x12",
        PrecioMayor: 10500,
        PrecioMinorista: null,
        Categoria: "Medias",
        TipoMedida: null,
        Talle: [],
        Descripcion: null,
        Color: [],
    },
    {
        Codigo: "M09",
        Estado: null,
        Img: "Medias/M09-img1",
        Producto: "Altomax Varón 3/4",
        PrecioMayor: null,
        PrecioMinorista: null,
        Categoria: "Medias",
        TipoMedida: null,
        Talle: [],
        Descripcion: null,
        Color: [],
    },

    {
        Codigo: "M10",
        Estado: null,
        Img: "Medias/M10-img1",
        Producto: "Media MD Dama/Varón 3/4",
        PrecioMayor: null,
        PrecioMinorista: null,
        Categoria: "Medias",
        TipoMedida: null,
        Talle: [],
        Descripcion: null,
        Color: [],
    },

    {
        Codigo: "M11",
        Estado: null,
        Img: "Medias/M11-img1",
        Producto: "Super Balance Dama 3/4",
        PrecioMayor: null,
        PrecioMinorista: null,
        Categoria: "Medias",
        TipoMedida: null,
        Talle: [],
        Descripcion: null,
        Color: [],
    },

    {
        Codigo: "M12",
        Estado: null,
        Img: "Medias/M12-img1",
        Producto: "SB Varon 3/4",
        PrecioMayor: null,
        PrecioMinorista: null,
        Categoria: "Medias",
        TipoMedida: null,
        Talle: [],
        Descripcion: null,
        Color: [],
    },

    {
        Codigo: "M13",
        Estado: null,
        Img: "Medias/M13-img1",
        Producto: "Deportiva Antideslizante Corta",
        PrecioMayor: null,
        PrecioMinorista: null,
        Categoria: "Medias",
        TipoMedida: null,
        Talle: [],
        Descripcion: null,
        Color: [],
    },

    {
        Codigo: "M14",
        Estado: null,
        Img: "Medias/M14-img1",
        Producto: "Deportiva Antideslizante Larga",
        PrecioMayor: null,
        PrecioMinorista: null,
        Categoria: "Medias",
        TipoMedida: null,
        Talle: [],
        Descripcion: null,
        Color: [],
    },

    {
        Codigo: "M15",
        Estado: null,
        Img: "Medias/M15-img1",
        Producto: "Media Invisible Dama/Varón",
        PrecioMayor: null,
        PrecioMinorista: null,
        Categoria: "Medias",
        TipoMedida: null,
        Talle: [],
        Descripcion: null,
        Color: [],
    },

    {
        Codigo: "M16",
        Estado: null,
        Img: "Medias/M16-img1",
        Producto: "Soque Alto MD Dama/Varón",
        PrecioMayor: null,
        PrecioMinorista: null,
        Categoria: "Medias",
        TipoMedida: null,
        Talle: [],
        Descripcion: null,
        Color: [],
    },

    {
        Codigo: "M17",
        Estado: null,
        Img: "Medias/M17-img1",
        Producto: "Soque Alto Men Varón",
        PrecioMayor: null,
        PrecioMinorista: null,
        Categoria: "Medias",
        TipoMedida: null,
        Talle: [],
        Descripcion: null,
        Color: [],
    },

    {
        Codigo: "M18",
        Estado: null,
        Img: "Medias/M18-img1",
        Producto: "SoqueAlto SBalance Dama/Varón",
        PrecioMayor: null,
        PrecioMinorista: null,
        Categoria: "Medias",
        TipoMedida: null,
        Talle: [],
        Descripcion: null,
        Color: [],
    },

    {
        Codigo: "M19",
        Estado: null,
        Img: "Medias/M19-img1",
        Producto: "Soque M Dama",
        PrecioMayor: null,
        PrecioMinorista: null,
        Categoria: "Medias",
        TipoMedida: null,
        Talle: [],
        Descripcion: null,
        Color: [],
    },

    {
        Codigo: "M20",
        Estado: null,
        Img: "Medias/M20-img1",
        Producto: "Soque SBalance Dama",
        PrecioMayor: null,
        PrecioMinorista: null,
        Categoria: "Medias",
        TipoMedida: null,
        Talle: [],
        Descripcion: null,
        Color: [],
    },

    {
        Codigo: "M21",
        Estado: null,
        Img: "Medias/M21-img1",
        Producto: "Soque Socmark Dama",
        PrecioMayor: null,
        PrecioMinorista: null,
        Categoria: "Medias",
        TipoMedida: null,
        Talle: [],
        Descripcion: null,
        Color: [],
    },

    {
        Codigo: "M22",
        Estado: null,
        Img: "Medias/M22-img1",
        Producto: "Termico Sbalanse Dama/Varón",
        PrecioMayor: null,
        PrecioMinorista: null,
        Categoria: "Medias",
        TipoMedida: null,
        Talle: [],
        Descripcion: null,
        Color: [],
    },

    {
        Codigo: "M23",
        Estado: null,
        Img: "Medias/M23-img1",
        Producto: "Soquete Varón",
        PrecioMayor: null,
        PrecioMinorista: null,
        Categoria: "Medias",
        TipoMedida: null,
        Talle: [],
        Descripcion: null,
        Color: [],
    },

    {
        Codigo: "M24",
        Estado: null,
        Img: "Medias/M24-img1",
        Producto: "Soquete ViMas Dama",
        PrecioMayor: null,
        PrecioMinorista: null,
        Categoria: "Medias",
        TipoMedida: null,
        Talle: [],
        Descripcion: null,
        Color: [],
    },

    {
        Codigo: "M25",
        Estado: null,
        Img: "Medias/M25-img1",
        Producto: "Termica Piel",
        PrecioMayor: null,
        PrecioMinorista: null,
        Categoria: "Medias",
        TipoMedida: null,
        Talle: [],
        Descripcion: null,
        Color: [],
    },

    {
        Codigo: "VE01",
        Estado: null,
        Img: "Vestimenta/VE01-img1",
        Producto: "Calza Corta deportiva",
        PrecioMayor: 14000,
        PrecioMinorista: null,
        Categoria: "Vestimenta",
        TipoMedida: "Talle",
        Talle: ["S/M", "L/XL"],
        Descripcion: "Consultar por Docena.   Talles:S/M - L/XL   Colores: Consultar",
        Color: [],
    },
    {
        Codigo: "VE02",
        Estado: null,
        Img: "Vestimenta/VE02-img1",
        Producto: "Calza deportiva lisa",
        PrecioMayor: 12000,
        PrecioMinorista: null,
        Categoria: "Vestimenta",
        TipoMedida: null,
        Talle: [],
        Descripcion: "Calza deportiva lisa con funce",
        Color: [],
    },
    {
        Codigo: "VE03",
        Estado: null,
        Img: "Vestimenta/VE03-img1",
        Producto: "Calza efecto piel",
        PrecioMayor: 10000,
        PrecioMinorista: null,
        Categoria: "Vestimenta",
        TipoMedida: null,
        Talle: [],
        Descripcion: null,
        Color: [],
    },
    {
        Codigo: "VE04",
        Estado: null,
        Img: "Vestimenta/VE04-img1",
        Producto: "Cocot Medias 3/4 Mulifilamento",
        PrecioMayor: 5000,
        PrecioMinorista: null,
        Categoria: "Vestimenta",
        TipoMedida: null,
        Talle: [],
        Descripcion: "Un pack de 2 pares x 5000$ Colores: Negro - Tostado - Natural",
        Color: ["Negro", "Tostado", "Natural", "Surtido"],
    },
    {
        Codigo: "VE05",
        Estado: null,
        Img: "Vestimenta/VE05-img1",
        Producto: "MX PantiMedia",
        PrecioMayor: 6000,
        PrecioMinorista: null,
        Categoria: "Vestimenta",
        TipoMedida: null,
        Talle: [],
        Descripcion: "Colores: Tostado - Negro - Natural",
        Color: ["Tostado", "Negro", "Natural"],
    },
    {
        Codigo: "VE06",
        Estado: null,
        Img: "Vestimenta/VE06-img1",
        Producto: "PantiMedia Común",
        PrecioMayor: 2500,
        PrecioMinorista: null,
        Categoria: "Vestimenta",
        TipoMedida: null,
        Talle: [],
        Descripcion: "Unico color el de la imagen. ¡Un pack de 3pares x2500$!",
        Color: [],
    },
    {
        Codigo: "VE07",
        Estado: null,
        Img: "Vestimenta/VE07-img1",
        Producto: "Top Smart sexy",
        PrecioMayor: 6000,
        PrecioMinorista: null,
        Categoria: "Vestimenta",
        TipoMedida: "Talle",
        Talle: ["M/L", "XL/XXL"],
        Descripcion: "Consultar por Docena y Colores",
        Color: [],
    },
    {
        Codigo: "VE08",
        Estado: null,
        Img: "Vestimenta/VE08-img1",
        Producto: "Conjunto Sakali",
        PrecioMayor: null,
        PrecioMinorista: null,
        Categoria: "Vestimenta",
        TipoMedida: "Talle",
        Talle: ["XL"],
        Descripcion: "Consultar por Docena.   Colores: Verde Fluor - Violeta - Verde Pastel - Naranja - Azul - Gris - Negro",
        Color: [
            "Verde Fluor",
            "Violeta",
            "Verde Pastel",
            "Naranja",
            "Azul",
            "Gris",
            "Negro",
            "Surtido"
        ],
    },
    {
        Codigo: "VE09",
        Estado: null,
        Img: "Vestimenta/VE09-img1",
        Producto: "Top D´lirio",
        PrecioMayor: 7500,
        PrecioMinorista: null,
        Categoria: "Vestimenta",
        TipoMedida: "Talle",
        Talle: ["L/XL", "XXL/XXXL"],
        Descripcion: "Consultar por Docena.   Colores: Rosa - Gris - Negro - Azul - Fucsia",
        Color: [
            "Rosa",
            "Gris",
            "Negro",
            "Azul",
            "Fucsia",
            "Surtido"
        ],
    },
];


const TodasImg = [
    {
        codigo: "P22",
        Imagenes: [
            "Plantillas/P01-img1",
            "Plantillas/P01-img2",
            "Plantillas/P01-img3",
            "Plantillas/P01-img4",
        ],
    },
    {
        codigo: "P24",
        Imagenes: [
            "Plantillas/P02-img1",
            "Plantillas/P02-img2",
            "Plantillas/P02-img3",
            "Plantillas/P02-img4",
        ],
    },
    {
        codigo: "P01",
        Imagenes: [
            "Plantillas/P01-img1",
            "Plantillas/P01-img2",
            "Plantillas/P01-img3",
            "Plantillas/P01-img4",
        ],
    },
    {
        codigo: "P02",
        Imagenes: [
            "Plantillas/P02-img1",
            "Plantillas/P02-img2",
            "Plantillas/P02-img3",
            "Plantillas/P02-img4",
        ],
    },
    {
        codigo: "P03",
        Imagenes: [
            "Plantillas/P03-img1",
            "Plantillas/P03-img2",
            "Plantillas/P03-img3",
        ],
    },
    {
        codigo: "P04",
        Imagenes: [
            "Plantillas/P04-img1",
            "Plantillas/P04-img2",
            "Plantillas/P04-img3",
        ],
    },
    {
        codigo: "P05",
        Imagenes: [
            "Plantillas/P05-img1",
            "Plantillas/P05-img2",
        ],
    },
    {
        codigo: "P06",
        Imagenes: [
            "Plantillas/P06-img1",
            "Plantillas/P06-img2",
            "Plantillas/P06-img3",
            "Plantillas/P06-img4",
        ],
    },
    {
        codigo: "P07",
        Imagenes: [
            "Plantillas/P07-img1",
            "Plantillas/P07-img2",
            "Plantillas/P07-img3",
        ],
    },
    {
        codigo: "P08",
        Imagenes: [
            "Plantillas/P08-img1",
            "Plantillas/P08-img2",
            "Plantillas/P08-img3",
            "Plantillas/P08-img4",
        ],
    },
    {
        codigo: "P09",
        Imagenes: [
            "Plantillas/P09-img1",
            "Plantillas/P09-img2",
            "Plantillas/P09-img3",
            "Plantillas/P09-img4",
        ],
    },
    {
        codigo: "P10",
        Imagenes: [
            "Plantillas/P10-img1",
            "Plantillas/P10-img2",
            "Plantillas/P10-img3",
            "Plantillas/P10-img4",
        ],
    },
    {
        codigo: "P11",
        Imagenes: [
            "Plantillas/P11-img1",
            "Plantillas/P11-img2",
            "Plantillas/P11-img3"
        ],
    },

    {
        codigo: "MODELO00",
        Imagenes: [
            "Llaveros/Modelo00-img1",
            "Llaveros/Modelo00-img2",
            "Llaveros/Modelo00-img3",
        ],
    },
    {
        codigo: "MODELO01",
        Imagenes: [
            "Llaveros/Modelo01-img1",
            "Llaveros/Modelo01-img2",
            "Llaveros/Modelo01-img3",
        ],
    },
    {
        codigo: "MODELO02",
        Imagenes: [
            "Llaveros/Modelo02-img1",
            "Llaveros/Modelo02-img2",
        ],
    },
    {
        codigo: "MODELO03",
        Imagenes: [
            "Llaveros/Modelo03-img1",
            "Llaveros/Modelo03-img2",
            "Llaveros/Modelo03-img3",
        ],
    },
    {
        codigo: "MODELO04",
        Imagenes: [
            "Llaveros/Modelo04-img1",
            "Llaveros/Modelo04-img2",
            "Llaveros/Modelo04-img3",
        ],
    },
    {
        codigo: "MODELO07",
        Imagenes: [
            "Llaveros/Modelo07-img1",
            "Llaveros/Modelo07-img2",
            "Llaveros/Modelo07-img3",
        ],
    },
    {
        codigo: "MODELO08",
        Imagenes: [
            "Llaveros/Modelo08-img1",
            "Llaveros/Modelo08-img2",
            "Llaveros/Modelo08-img3",
        ],
    },
    {
        codigo: "MODELO09",
        Imagenes: [
            
            "Llaveros/Modelo09-img1",
            "Llaveros/Modelo09-img2",
            "Llaveros/Modelo09-img3",
            "Llaveros/Modelo09-img4",
            "Llaveros/Modelo09-img5",
            "Llaveros/Modelo09-img6",
        ],
    },
    {
        codigo: "MODELO10",
        Imagenes: [
            "Llaveros/Modelo10-img1",
            "Llaveros/Modelo10-img2",
            "Llaveros/Modelo10-img3",
        ],
    },
    {
        codigo: "MODELO11",
        Imagenes: [
            "Llaveros/Modelo11-img1",
        ],
    },
    {
        codigo: "MODELO12",
        Imagenes: [
            "Llaveros/Modelo12-img1",
        ],
    },
    {
        codigo: "MODELO13",
        Imagenes: [
            "Llaveros/Modelo13-img1",
            "Llaveros/Modelo13-img2",
            "Llaveros/Modelo13-img3",
        ],
    },
    {
        codigo: "MODELO14",
        Imagenes: [
            "Llaveros/Modelo14-img1",
            "Llaveros/Modelo14-img2",
            "Llaveros/Modelo14-img3",
        ],
    },

    {
        codigo: "ArtiPr01",
        Imagenes: [
            "ArticulosDePerro/ArtiPr01-img1",
            "ArticulosDePerro/ArtiPr01-img2",
        ],
    },
    {
        codigo: "ArtiPr02",
        Imagenes: [
            "ArticulosDePerro/ArtiPr02-img1",
            "ArticulosDePerro/ArtiPr02-img2",
            "ArticulosDePerro/ArtiPr02-img3",
            "ArticulosDePerro/ArtiPr02-img4",
        ],
    },
    {
        codigo: "ArtiPr03",
        Imagenes: [
            "ArticulosDePerro/ArtiPr03-img1",
            "ArticulosDePerro/ArtiPr03-img2",
            "ArticulosDePerro/ArtiPr03-img3",
            "ArticulosDePerro/ArtiPr03-img4",
        ],
    },

    {
        codigo: "M01",
        Imagenes: [
            "Medias/M01-img1",
            "Medias/M01-img2",
        ],
    },
    {
        codigo: "M02",
        Imagenes: [
            "Medias/M02-img1",
            "Medias/M02-img2",
            "Medias/M02-img3",
            "Medias/M02-img4",
            "Medias/M02-img5"
        ],
    },
    {
        codigo: "M03",
        Imagenes: [
            "Medias/M03-img1",
            "Medias/M03-img2",
            "Medias/M03-img3"
        ],
    },
    {
        codigo: "M04",
        Imagenes: [
            "Medias/M04-img1",
        ],
    },
    {
        codigo: "M05",
        Imagenes: [
            "Medias/M05-img1",
            "Medias/M05-img2",
            "Medias/M05-img3",
            "Medias/M05-img4",
            "Medias/M05-img5"
        ],
    },
    {
        codigo: "M06",
        Imagenes: [
            "Medias/M06-img1",
            "Medias/M06-img2",
        ],
    },
    {
        codigo: "M07",
        Imagenes: [
            "Medias/M07-img1",
            "Medias/M07-img2",
            "Medias/M07-img3"
        ],
    },
    {
        codigo: "M08",
        Imagenes: [
            "Medias/M08-img1",
            "Medias/M08-img2",
            "Medias/M08-img3",
            "Medias/M08-img4",
            "Medias/M08-img5",
            "Medias/M08-img6"
        ],
    },

    {
        codigo: "M09",
        Imagenes: [
            "Medias/M09-img1",
            "Medias/M09-img2",
            "Medias/M09-img3",
            "Medias/M09-img4",
            "Medias/M09-img5",
            "Medias/M09-img6",
        ],
    },

    {
        codigo: "M10",
        Imagenes: [
            "Medias/M10-img1",
            "Medias/M10-img2",
            "Medias/M10-img3",
            "Medias/M10-img4",
            "Medias/M10-img5",
            "Medias/M10-img6",
            "Medias/M10-img7",
            "Medias/M10-img8",
            "Medias/M10-img9",
        ],
    },

    {
        codigo: "M11",
        Imagenes: [
            "Medias/M11-img1",
            "Medias/M11-img2",
            "Medias/M11-img3",
            "Medias/M11-img4",
            "Medias/M11-img5",
            "Medias/M11-img6",
        ],
    },

    {
        codigo: "M12",
        Imagenes: [
            "Medias/M12-img1",
            "Medias/M12-img2",
            "Medias/M12-img3",
        ],
    },

    {
        codigo: "M13",
        Imagenes: [
            "Medias/M13-img1",
            "Medias/M13-img2",
            "Medias/M13-img3",
            "Medias/M13-img4",
        ],
    },

    {
        codigo: "M14",
        Imagenes: [
            "Medias/M14-img1",
            "Medias/M14-img2",
            "Medias/M14-img3",
        ],
    },

    {
        codigo: "M15",
        Imagenes: [
            "Medias/M15-img1",
            "Medias/M15-img2",
            "Medias/M15-img3",
            "Medias/M15-img4",
            "Medias/M15-img5",
            "Medias/M15-img6",
        ],
    },

    {
        codigo: "M16",
        Imagenes: [
            "Medias/M16-img1",
            "Medias/M16-img2",
            "Medias/M16-img3",
            "Medias/M16-img4",
            "Medias/M16-img5",
            "Medias/M16-img6",
        ],
    },

    {
        codigo: "M17",
        Imagenes: [
            "Medias/M17-img1",
            "Medias/M17-img2",
            "Medias/M17-img3",
        ],
    },

    {
        codigo: "M18",
        Imagenes: [
            "Medias/M18-img1",
            "Medias/M18-img2",
            "Medias/M18-img3",
            "Medias/M18-img4",
            "Medias/M18-img5",
            "Medias/M18-img6",
            "Medias/M18-img7",
            "Medias/M18-img8",
            "Medias/M18-img9",
        ],
    },

    {
        codigo: "M19",
        Imagenes: [
            "Medias/M19-img1",
            "Medias/M19-img2",
            "Medias/M19-img3",
        ],
    },

    {
        codigo: "M20",
        Imagenes: [
            "Medias/M20-img1",
            "Medias/M20-img2",
            "Medias/M20-img3",
            "Medias/M20-img4",
            "Medias/M20-img5",
            "Medias/M20-img6",
        ],
    },

    {
        codigo: "M21",
        Imagenes: [
            "Medias/M21-img1",
            "Medias/M21-img2",
            "Medias/M21-img3"
        ],
    },

    {
        codigo: "M22",
        Imagenes: [
            "Medias/M22-img1",
            "Medias/M22-img2",
            "Medias/M22-img3",
            "Medias/M22-img4",
            "Medias/M22-img5",
            "Medias/M22-img6",
            "Medias/M22-img7",
            "Medias/M22-img8",
            "Medias/M22-img9",
            "Medias/M22-img10",
            "Medias/M22-img11",
            "Medias/M22-img12",
        ],
    },

    {
        codigo: "M23",
        Imagenes: [
            "Medias/M23-img1",
            "Medias/M23-img2",
            "Medias/M23-img3"
        ],
    },

    {
        codigo: "M24",
        Imagenes: [
            "Medias/M24-img1",
            "Medias/M24-img2",
            "Medias/M24-img3"
        ],
    },

    {
        codigo: "M25",
        Imagenes: [
            "Medias/M25-img1",
            "Medias/M25-img2",
            "Medias/M25-img3",
            "Medias/M25-img4",
        ],
    },
    {
        codigo: "VE01",
        Imagenes: [
            "Vestimenta/VE01-img1",
            "Vestimenta/VE01-img2",
            "Vestimenta/VE01-img3",
            "Vestimenta/VE01-img4"
        ],
    },
    {
        codigo: "VE02",
        Imagenes: [
            "Vestimenta/VE02-img1",
            "Vestimenta/VE02-img2",
            "Vestimenta/VE02-img3",
            "Vestimenta/VE02-img4"
        ],
    },
    {
        codigo: "VE03",
        Imagenes: [
            "Vestimenta/VE03-img1",
        ],
    },
    {
        codigo: "VE04",
        Imagenes: [
            "Vestimenta/VE04-img1",
            "Vestimenta/VE04-img2",
            "Vestimenta/VE04-img3",
        ],
    },
    {
        codigo: "VE05",
        Imagenes: [
            "Vestimenta/VE05-img1",
            "Vestimenta/VE05-img2",
            "Vestimenta/VE05-img3"
        ],
    },
    {
        codigo: "VE06",
        Imagenes: [
            "Vestimenta/VE06-img1",
            "Vestimenta/VE06-img2",
            "Vestimenta/VE06-img3"
        ],
    },
    {
        codigo: "VE07",
        Imagenes: [
            "Vestimenta/VE07-img1",
            "Vestimenta/VE07-img2",
            "Vestimenta/VE07-img3",
            "Vestimenta/VE07-img4"
        ],
    },
    {
        codigo: "VE08",
        Imagenes: [
            "Vestimenta/VE08-img1",
        ],
    },
    {
        codigo: "VE09",
        Imagenes: [
            "Vestimenta/VE09-img1",
            "Vestimenta/VE09-img2",
        ],
    },
];